name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    - name: Install Dependencies
      run:  npm install
      working-directory: ./webpage
    - name: Build
      env:
        NODE_ENV: production
      working-directory: ./webpage
      run: |
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: webpage/dist # The folder the action should deploy.

 
